export class QuarkStates {
  static HTTP_STATES = {
    SUCCCESS: 200,
    CREATE_SUCCESS: 201,
    UPDATE_SUCCESS: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    NOT_FOUND: 404,
    DUPLICATE_DATA: 422,
    INTERNAL_SERVER_ERROR: 500
  };
}
